#!/bin/bash
read -p "Enter a string:  " str
reverse=""
for(( i=${#str}-1; i>=0 ; i-- ))
do
reverse=$reverse${str:$i:1}
done
echo "Reversed string:  $reverse"
if [ $str == $reverse ]; then
 echo "It is a pallindrome string "
else
echo "It is not a pallindrome string "
fi
